import { StyleSheet,Dimensions } from "react-native"

const Dibujar=StyleSheet.create({
    contenedor:{
      width:'100%',
      padding:20
    },
    titulo:{
      fontSize:20,
      color:"pink"
    },
    textinput:{
      borderColor:'purple',
      borderWidth:1,
      borderRadius:15,
      width:Dimensions.get("screen").width*0.6,
      paddingLeft:"0.2%"
    },
    text:{
      fontSize:16,
      color:"white",
    },
    wtext:{
      fontSize:16,
      color:"red"
    },
    inputcontainer:{
      marginTop:20,
      flexDirection:"row",
      justifyContent:"space-between"
    },
    boton:{
      width:Dimensions.get("screen").width*0.25,
      backgroundColor:'pink',
      justifyContent:"center",
      alignItems:"center",
      borderRadius:15
    },
    tareascontenedor:{
      paddingVertical:20,
      borderBottomColor:"pink",
      borderBottomWidth:5,
      flexDirection:'row',
      justifyContent:'space-between'
    },
    TextoDone:{
      fontSize:16,
      color:"white",
      textDecorationLine:"line-through"
    },
    removeBoton:{
      backgroundColor:'r',
      justifyContent:'center',
      alignItems:'center',
      paddingHorizontal:15,
      borderRadius:10
    }
  })
  export default Dibujar